

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # 每个微服务都有单独的数据存储，这里为了简单，都是用同一个
    url: jdbc:mysql://localhost:3306/db_ordering?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  
  # rabbitmq的配置，不配置就会使用默认的配置
  rabbitmq: 
    host: localhost
    port: 5672
    username: guest
    password: guest
    
env:
  dev5
